name: Domain Değişiklik Kontrolü

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 11 */9 * * *

jobs:
  DomainKontrol:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v4

      - name: Python 3.11.8 Yükle
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Python Sürümünü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik cloudscraper pycryptodome

      - name: Betiği Çalıştır
        run: python KONTROL.py

      - name: Değişiklik Kontrolü
        id: diff_check
        run: |
          git diff --quiet . || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Pull Request Oluştur ve Otomatik Merge Et
        if: steps.diff_check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: domain-degisikligi
          title: "♻️ Domain Değişikliği"
          body: |
            🔄 Otomatik tespit edilen domain değişiklikleri uygulandı.

            📂 İlgili dosyalar güncellendi. Lütfen kontrol edin.
          commit-message: "♻️ Domain Değişikliği"
          labels: otomatik, domain-güncelleme
          auto-merge: true
          merge-method: squash
